"""
Site configurations for multi-source Mongolian news crawler.
Each site defines: entry point, listing parser, article parser, and pagination.
"""

SITES = [
    {
        "name": "police.gov.mn",
        "label": "警察总局",
        "lang": "mn",
        "home": "https://police.gov.mn/home",
        "article_url": "https://police.gov.mn/a/{id}",
        # --- Listing (homepage) ---
        "list_selectors": {
            "article_links": "a[href^='/a/']",
            "link_pattern": r"/a/(\d+)",
            "date_nearby": "span.date",
        },
        # --- Article detail ---
        "article_selectors": {
            "title": "h2.article-view-name, title",
            "date": "span.date",
            "date_regex": r"(\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2})",
            "date_regex_fallback": r"(\d{4}-\d{2}-\d{2})",
            "content": "article p, .article-view-content p, .uk-article p, p",
            "category": "ul.uk-breadcrumb li:last-child",
        },
        "date_format": "ymd",
        "paginate": None,  # ID-based crawling
    },
    {
        "name": "nfa.gov.mn",
        "label": "法医总局",
        "lang": "mn",
        "home": "https://nfa.gov.mn/",
        "news_list": "https://nfa.gov.mn/site/cat/1",
        "article_url": "https://nfa.gov.mn/site/single/{id}",
        "list_selectors": {
            "article_links": "a[href*='/site/single/']",
            "link_pattern": r"/site/single/(\d+)",
            "title_in_link": True,
        },
        "article_selectors": {
            "title": "h1, .news-title",
            "date": "li:has(.fa-calendar), span.date",
            "date_regex": r"(\d{4}-\d{2}-\d{2})",
            "date_regex_fallback": r"(\d{4}\.\d{2}\.\d{2})",
            "content": ".news-content p, article p, .content p, p",
            "category": ".breadcrumb li:last-child, .category",
        },
        "date_format": "ymd",
        "paginate": None,
    },
    {
        "name": "ncmh.gov.mn",
        "label": "精神卫生中心",
        "lang": "mn",
        "home": "https://www.ncmh.gov.mn/posts",
        "news_list": "https://www.ncmh.gov.mn/posts?page={page}",
        "article_url": "https://www.ncmh.gov.mn/post/{slug}",
        "list_selectors": {
            "article_links": "a[href*='/post/']",
            "link_pattern": r"/post/(.+)",
            "date_nearby_selector": "span, small, .date",
        },
        "article_selectors": {
            "title": "h1",
            "date": None,  # embedded in content - extract via regex
            "date_regex": r"(\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2})",
            "date_regex_fallback": r"(\d{4}-\d{2}-\d{2})",
            "content": "article p, .post-content p, .container p, p",
            "category": ".breadcrumb li:last-child",
        },
        "date_format": "ymd_hms",
        "paginate": {"param": "page", "start": 1, "max": 10},
    },
    {
        "name": "ikon.mn",
        "label": "Ikon新闻",
        "lang": "mn",
        "home": "https://ikon.mn/",
        "news_list": "https://ikon.mn/l/{cat}",
        "article_url": "https://ikon.mn/n/{id}",
        "rss": "https://ikon.mn/rss",
        "list_selectors": {
            "article_links": "a[href^='/n/']",
            "link_pattern": r"/n/(\w+)",
            "date_nearby_selector": "time, .time, .date, small",
        },
        "article_selectors": {
            "title": "h1",
            "date": "time, .article-date, .pub-date",
            "date_regex": r"(\d{4}-\d{2}-\d{2})",
            "date_regex_fallback": r"(\d{4}\.\d{2}\.\d{2})",
            "content": "article p, .article-content p, .news-content p, .post-content p, p",
            "category": ".category a, .section a",
        },
        "date_format": "ymd",
        "paginate": None,
    },
    {
        "name": "shuum.mn",
        "label": "Shuum新闻",
        "lang": "mn",
        "home": "https://shuum.mn/",
        "news_list": "https://shuum.mn/category/{cat}",
        "article_url": "https://shuum.mn/news-detail/{id}",
        "list_selectors": {
            "article_links": "a[href*='/news-detail/']",
            "link_pattern": r"/news-detail/(\d+)",
            "date_nearby_selector": ".date, small, span",
        },
        "article_selectors": {
            "title": "h1",
            "date": ".date, .news-date, .post-date",
            "date_regex": r"(\d{4}/\d{2}/\d{2})",
            "date_regex_fallback": r"(\d{4}-\d{2}-\d{2})",
            "content": ".news-content p, article p, .post-body p, .detail-content p, p",
            "category": ".category, .breadcrumb a:last-child",
        },
        "date_format": "ymd_slash",
        "paginate": None,
    },
    {
        "name": "odkb-csto.org",
        "label": "CSTO/ODKB",
        "lang": "ru",
        "home": "https://odkb-csto.org/",
        "news_list": "https://odkb-csto.org/news/news_odkb/",
        "article_url": "https://odkb-csto.org{path}",
        "list_selectors": {
            "article_links": "a[href*='/news/news_odkb/'], a[href*='/news/smi/'], a[href*='/news/speech/']",
            "link_pattern": r"(/news/[^\s\"']+)",
            "date_nearby_selector": ".date, .news-date, time",
        },
        "article_selectors": {
            "title": "h1",
            "date": ".date, .news-date, time, b",
            "date_regex": r"(\d{2}\.\d{2}\.\d{4})",
            "date_regex_fallback": r"(\d{4}-\d{2}-\d{2})",
            "content": ".before .preview p, .news-text p, article p, .news-content p, .content p",
            "category": ".breadcrumb a:last-child",
        },
        "date_format": "dmY_dot",
        "paginate": None,
    },
    {
        "name": "montsame.mn",
        "label": "蒙通社",
        "lang": "mn",
        "home": "https://montsame.mn/mn/",
        "news_list": "https://montsame.mn/mn/",
        "article_url": "https://montsame.mn/mn/read/{id}",
        "list_selectors": {
            "article_links": "a[href*='/read/']",
            "link_pattern": r"/read/(\d+)",
            "date_nearby_selector": "time, .date, .time",
        },
        "article_selectors": {
            "title": "h1, h3, .article-title",
            "date": "time, .date, .pub-date",
            "date_regex": r"(\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2})",
            "date_regex_fallback": r"(\d{4}-\d{2}-\d{2})",
            "content": "article p, .article-body p, .read-content p, .news-content p, p",
            "category": ".category a, .breadcrumb a:last-child",
        },
        "date_format": "ymd_hms",
        "paginate": None,
    },
    {
        "name": "unodc.org",
        "label": "UNODC",
        "lang": "en",
        "home": "https://www.unodc.org/unodc/frontpage/index.html",
        "rss": "https://www.unodc.org/unodc/feed/stories.xml",
        "article_url": "https://www.unodc.org{path}",
        "list_selectors": {
            "article_links": "a[href*='/frontpage/'], a[href*='/news/'], a[href*='/press/']",
            "link_pattern": r"(/unodc/\S+\.html)",
            "date_nearby_selector": ".date, time, .field-date",
        },
        "article_selectors": {
            "title": "h1",
            "date": ".date, time, .field-date, .published-date",
            "date_regex": r"(\d{1,2}\s+\w+\s+\d{4})",
            "date_regex_fallback": r"(\d{2}/\d{2}/\d{4})",
            "content": "article p, .story-content p, .field-body p, .content p, p",
            "category": ".category, .section, .breadcrumb a:last-child",
        },
        "date_format": "text",
        "paginate": None,
    },
    {
        "name": "mojha.gov.mn",
        "label": "司法内务部",
        "lang": "mn",
        "home": "https://mojha.gov.mn",
        "news_list": "https://mojha.gov.mn/news",
        "article_url": "https://mojha.gov.mn/news/{id}",
        "requires_js": True,
        "list_selectors": {
            "article_links": "a[href*='/news/']",
            "link_pattern": r"/news/(\d+)",
        },
        "article_selectors": {
            "title": "h1",
            "date": ".date, time",
            "date_regex": r"(\d{4}-\d{2}-\d{2})",
            "date_regex_fallback": r"(\d{4}\.\d{2}\.\d{2})",
            "content": "article p, .content p, p",
        },
        "date_format": "ymd",
        "paginate": None,
    },
    {
        "name": "nema.gov.mn",
        "label": "国家应急管理局",
        "lang": "mn",
        "home": "https://nema.gov.mn/",
        "news_list": "https://nema.gov.mn/posts",
        "article_url": "https://nema.gov.mn/post/{id}",
        "ssl_verify": False,
        "list_selectors": {
            "article_links": "a[href*='/post/']",
            "link_pattern": r"/post/(\d+)",
        },
        "article_selectors": {
            "title": "h1",
            "date": None,
            "date_regex": r"(\d{4}/\d{2}/\d{2})",
            "date_regex_fallback": r"(\d{4}-\d{2}-\d{2})",
            "content": ".html-body p, #rich-text p, .post-item p, section p, p",
        },
        "date_format": "ymd_slash",
        "paginate": None,
    },
    {
        "name": "moe.gov.mn",
        "label": "教育部",
        "lang": "mn",
        "home": "https://moe.gov.mn/",
        "news_list": "https://moe.gov.mn/posts?category_id=11390",
        "article_url": "https://moe.gov.mn/post/{id}",
        "list_selectors": {
            "article_links": "a[href*='/post/']",
            "link_pattern": r"/post/(\d+)",
        },
        "article_selectors": {
            "title": "h1",
            "date": None,
            "date_regex": r"(\d{4}-\d{2}-\d{2})",
            "date_regex_fallback": r"(\d{4}/\d{2}/\d{2})",
            "content": ".entry-content p, .content-block-body p, .post-content p, p",
        },
        "date_format": "ymd",
        "paginate": None,
    },
    {
        "name": "moh.gov.mn",
        "label": "卫生部",
        "lang": "mn",
        "home": "https://www.moh.gov.mn/",
        "news_list": "https://www.moh.gov.mn/index.php/news/t/1",
        "article_url": "https://www.moh.gov.mn/index.php/news/{id}",
        "ssl_verify": False,
        "list_selectors": {
            "article_links": "a[href*='/news/']",
            "link_pattern": r"/news/(\d+)",
        },
        "article_selectors": {
            "title": "h1",
            "date": None,
            "date_regex": r"(\d{4}-\d{2}-\d{2})",
            "date_regex_fallback": r"(\d{4}/\d{2}/\d{2})",
            "content": "#content p, .news-content p, .content p, p",
        },
        "date_format": "ymd",
        "paginate": None,
    },
    # === 新增：毒品相关执法/司法/新闻来源 ===
    {
        "name": "prokuror.mn",
        "label": "检察总署",
        "lang": "mn",
        "home": "https://prokuror.mn",
        "news_list": "https://prokuror.mn/news",
        "article_url": "https://prokuror.mn/news/{id}",
        "list_selectors": {
            "article_links": "a[href*='/news/']",
            "link_pattern": r"/news/(\d+)",
            "date_nearby_selector": ".date, time, small",
        },
        "article_selectors": {
            "title": "h1",
            "date": ".date, time",
            "date_regex": r"(\d{4}-\d{2}-\d{2})",
            "date_regex_fallback": r"(\d{4}\.\d{2}\.\d{2})",
            "content": "article p, .news-content p, .content p, p",
            "category": ".breadcrumb li:last-child",
        },
        "date_format": "ymd",
        "paginate": None,
    },
    {
        "name": "gogo.mn",
        "label": "Gogo新闻",
        "lang": "mn",
        "home": "https://gogo.mn/",
        "news_list": "https://gogo.mn/",
        "article_url": "https://gogo.mn/r/{id}",
        "list_selectors": {
            "article_links": "a[href*='/r/']",
            "link_pattern": r"/r/(\w+)",
            "date_nearby_selector": "time, .date, .time, small",
        },
        "article_selectors": {
            "title": "h1",
            "date": "time, .date, .pub-date",
            "date_regex": r"(\d{4}-\d{2}-\d{2})",
            "date_regex_fallback": r"(\d{4}\.\d{2}\.\d{2})",
            "content": "article p, .article-content p, .news-content p, .read-content p, p",
            "category": ".category a, .breadcrumb a:last-child",
        },
        "date_format": "ymd",
        "paginate": None,
    },
    {
        "name": "unuudur.mn",
        "label": "今日报",
        "lang": "mn",
        "home": "https://unuudur.mn/",
        "news_list": "https://unuudur.mn/",
        "article_url": "https://unuudur.mn/content/{id}",
        "list_selectors": {
            "article_links": "a[href*='/content/']",
            "link_pattern": r"/content/(\d+)",
            "date_nearby_selector": "time, .date, .time, small",
        },
        "article_selectors": {
            "title": "h1",
            "date": "time, .date",
            "date_regex": r"(\d{4}-\d{2}-\d{2})",
            "date_regex_fallback": r"(\d{4}\.\d{2}\.\d{2})",
            "content": "article p, .article-content p, .news-content p, .content p, p",
            "category": ".category a, .breadcrumb a:last-child",
        },
        "date_format": "ymd",
        "paginate": None,
    },
    {
        "name": "olloo.mn",
        "label": "Olloo新闻",
        "lang": "mn",
        "home": "https://olloo.mn/",
        "news_list": "https://olloo.mn/",
        "article_url": "https://olloo.mn/n/{id}",
        "list_selectors": {
            "article_links": "a[href*='/n/']",
            "link_pattern": r"/n/(\d+)",
            "date_nearby_selector": "time, .date, .time, small",
        },
        "article_selectors": {
            "title": "h1",
            "date": "time, .date",
            "date_regex": r"(\d{4}-\d{2}-\d{2})",
            "date_regex_fallback": r"(\d{4}\.\d{2}\.\d{2})",
            "content": "article p, .article-content p, .news-content p, .content p, p",
            "category": ".category a, .breadcrumb a:last-child",
        },
        "date_format": "ymd",
        "paginate": None,
    },
    {
        "name": "intr.gov.mn",
        "label": "内务部队",
        "lang": "mn",
        "home": "https://intr.gov.mn/",
        "news_list": "https://intr.gov.mn/news",
        "article_url": "https://intr.gov.mn/news/{id}",
        "list_selectors": {
            "article_links": "a[href*='/news/']",
            "link_pattern": r"/news/(\d+)",
            "date_nearby_selector": ".date, time, small",
        },
        "article_selectors": {
            "title": "h1",
            "date": ".date, time",
            "date_regex": r"(\d{4}-\d{2}-\d{2})",
            "date_regex_fallback": r"(\d{4}\.\d{2}\.\d{2})",
            "content": "article p, .news-content p, .content p, p",
            "category": ".breadcrumb li:last-child",
        },
        "date_format": "ymd",
        "paginate": None,
    },
]

# Sites that are known to be inaccessible (tried all known alternatives)
INACCESSIBLE = [
    {"name": "customs.gov.mn", "reason": "SSL handshake failure + HTTP 502 - server broken"},
    {"name": "news.mn", "reason": "SSL EOF + connection timeout on all variants"},
    {"name": "betelmongolia.org", "reason": "No news section - static brochure site"},
    {"name": "mohs.mn", "reason": "Redirects to empty Location header - use moh.gov.mn instead"},
]
